export const GET_COURSE_DETAILS_REQUESTED = 'GET_COURSE_DETAILS_REQUESTED';
export const GET_COURSE_DETAILS_FAILED = 'GET_COURSE_DETAILS_FAILED';
export const GET_COURSE_DETAILS_SUCCEEDED = 'GET_COURSE_DETAILS_SUCCEEDED';
