export const GET_DISCOVERY_ITEMS_REQUESTED = 'GET_DISCOVERY_ITEMS_REQUESTED';
export const GET_DISCOVERY_ITEMS_FAILED = 'GET_DISCOVERY_ITEMS_FAILED';
export const GET_DISCOVERY_ITEMS_SUCCEEDED = 'GET_DISCOVERY_ITEMS_SUCCEEDED';
