export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const REMIND_PASSWORD_REQUESTED = 'REMIND_PASSWORD_REQUESTED';
export const REMIND_PASSWORD_SUCCEEDED = 'REMIND_PASSWORD_SUCCEEDED';
export const REMIND_PASSWORD_FAILED = 'REMIND_PASSWORD_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';

export const AUTH_DATA_RETRIEVAL_REQUESTED = 'AUTH_DATA_RETRIEVAL_REQUESTED';
export const AUTH_DATA_RETRIEVAL_SUCCEEDED = 'AUTH_DATA_RETRIEVAL_SUCCEEDED';