export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const SET_FIELD_TOUCHED = 'SET_FIELD_TOUCHED';
export const SUBMIT_REQUESTED = 'SUBMIT_REQUESTED';
export const SUBMIT_SUCCEEDED = 'SUBMIT_SUCCEEDED';
export const SUBMIT_FAILED = 'SUBMIT_FAILED';
export const SET_ERRORS = 'SET_ERRORS';
